apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-pagerduty
  namespace: saas-framework
data:
  pagerduty.yaml: |
    global:
      pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'pagerduty'
      routes:
      - match:
          severity: critical
        receiver: 'pagerduty-critical'
    
    receivers:
    - name: 'pagerduty'
      pagerduty_configs:
      - service_key: 'PAGERDUTY_SERVICE_KEY'
        description: 'SaaS Platform Alert: {{ .GroupLabels.alertname }}'
    
    - name: 'pagerduty-critical'
      pagerduty_configs:
      - service_key: 'PAGERDUTY_CRITICAL_SERVICE_KEY'
        description: 'CRITICAL SaaS Platform Alert: {{ .GroupLabels.alertname }}'
        severity: 'critical'
