apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-infrastructure-staging
  namespace: argocd
  labels:
    environment: staging
spec:
  project: saas-platform
  
  source:
    repoURL: https://github.com/vhvcorp/go-infrastructure
    targetRevision: main
    path: kubernetes/overlays/staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-framework-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
