apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-app-of-apps
  namespace: argocd
spec:
  project: saas-platform
  
  source:
    repoURL: https://github.com/vhvcorp/go-infrastructure
    targetRevision: main
    path: argocd/applications
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
